name: "Destroy Infrastruktur"

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Prieller_Christian/Abgabe_2/terraform

    steps:
      - uses: actions/checkout@v4

      - name: OpenTofu installieren
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: "1.8.0"

      - name: State aus Cache laden
        uses: actions/cache/restore@v4
        with:
          path: ./Prieller_Christian/Abgabe_2/terraform/terraform.tfstate
          key: tfstate-prieller
          restore-keys: |
            tfstate-prieller-

      - name: Terraform Init
        run: tofu init

      - name: Terraform Destroy
        run: tofu destroy -auto-approve -no-color
        env:
          TF_VAR_exoscale_api_key: ${{ secrets.EXOSCALE_API_KEY }}
          TF_VAR_exoscale_api_secret: ${{ secrets.EXOSCALE_API_SECRET }}

      - name: Leeren State cachen
        uses: actions/cache/save@v4
        if: always()
        with:
          path: ./Prieller_Christian/Abgabe_2/terraform/terraform.tfstate
          key: tfstate-prieller-${{ github.run_id }}
