name: "Destroy Infrastruktur"

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Prieller_Christian/Abgabe_2/terraform

    steps:
      - uses: actions/checkout@v4

      - name: OpenTofu installieren
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: "1.8.0"

      - name: State laden
        uses: dawidd6/action-download-artifact@v6
        with:
          name: terraform-state
          path: ./Prieller_Christian/Abgabe_2/terraform
          workflow: deploy.yml
          search_artifacts: true

      - name: Terraform Init
        run: tofu init

      - name: Terraform Destroy
        run: tofu destroy -auto-approve -no-color
        env:
          TF_VAR_exoscale_api_key: ${{ secrets.EXOSCALE_API_KEY }}
          TF_VAR_exoscale_api_secret: ${{ secrets.EXOSCALE_API_SECRET }}
